version: '3.7'

services:  

  diagrams:
    build: src/main/docker/images/diagrams
    image: kalemena/mingrammer-diagrams:latest

  confluence:
    # build: .
    image: confluencepublisher/confluence-publisher-it:6.0.5
    ports:
     - "8090:8090"
     - "8091:8091"

  # publisher-confluence:
  #   image: confluencepublisher/confluence-publisher:0.0.0-SNAPSHOT
  #   user: ${DOCKER_USERID:-1000:1000}
  #   env_file:
  #     - .env-confluence
  #   # environment:
  #   #   - ATTRIBUTES={ "confluencePublisherVersion": "0.0.0-SNAPSHOT" }
  #   volumes:
  #     - ./build:/docs
