= Project 

ifdef::confluencePublisherVersion[]
include::/docs/_headers.confluence.adoc[]
endif::[]

//ifdef::env-github,confluencePublisherVersion[:outfilesuffix: .adoc]
//link:README{outfilesuffix}[README]

ifdef::env-github[]
:binariesdir: /docs/src/adoc/binaries
:giturl:
:imagesdir: /docs/src/adoc/images
//:sectlinks:
//:sectnums:
// Admonitions
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]

[NOTE]
====
The documentation is written in the form of AsciiDoc.

_Version of Confluence Publisher : {confluencePublisherVersion}_
====

== Description

Nowadays, projects hosted on GitHub often use a *documentation-as-code*, where documentation is written as text using formatting such as *Markdown* or *Asciidoc*

*AsciiDoc* is used here because this formatting offers much higher flexibility and features.

*Asciidoctor* is a fast text processor and publishing toolchain for converting AsciiDoc content to HTML5, EPUB3, PDF, DocBook 5






== Tools

This section describes tools commonly used to do perform proper documentation.

* Writing text:
** Visual Studio Code and plugins for link:https://github.com/plantuml/plantuml[PlantUML] and AsciiDoc.

* Diagrams:
** Architecture with link:https://diagrams.mingrammer.com/docs/guides/diagram[Diagrams]
** Classes, Use case, Flow diagrams with link:https://github.com/plantuml/plantuml[PlantUML]

* Publishing
** To PDF/HTML/EPUB : link:https://asciidoctor.org/[AsciiDoctor]
** To Confluence : link:https://github.com/confluence-publisher/confluence-publisher[Confluence-Publisher]

== Example

This repository has an example doc which demonstrates publication to the various destination mentioned above.

The sample documentation comes from link:https://github.com/confluence-publisher/confluence-publisher[] (for now)

.Building the toolkit
[source, bash]
----
$ make build
----

.Building diagrams with mingrammer tool
[source, bash]
----
# Create python assets under *src/adoc/assets* folder (e.g. architecture-hla.py)
$ make publishAssets

# PNG files will be available under *build/images* folder (e.g. architecture-hla.png)
----

[TIP]
====
Building assets is already part of next actions for PDF or Confluence publish
====

.Building the documentation as PDF
[source, bash]
----
$ make publishToPDF
----

[IMPORTANT]
====
The documentation PDF book will be found under *build/_SampleProject-Book.pdf*
====

.Confluence start/stop/clean
[source, bash]
----
$ confluence.start    # Wait a bit for this to settle !
$ confluence.logs
$ confluence.stop
$ confluence.clean
----

[IMPORTANT]
====
Confluence comes from link:https://github.com/confluence-publisher/confluence-publisher-it[]
This environment has a 3h timeframe license only for testing.

Confluence is available at link:http://localhost:8090[]

The following users are configured:
- admin/admin
- confluence-publisher-it/1234
====

.Building the documentation as Confluence
[source, bash]
----
$ make publishToConfluence
----

== Links

.Examples
* link:https://github.com/mraible/infoq-mini-book[InfoQ mini book]

.Diagrams
* link:https://kroki.io/[Kroki]
* link:https://github.com/BurntSushi/erd[ERD]












== How-To

=== Editing

Using *Visual Studio Code*, install plugings such as AsciiDoc in order to render the *.adoc* files.

Follow syntax as documented in link:https://asciidoctor.org/docs/user-manual[AsciiDoctor User Manual]

=== Building

Building the documentation can be done with targets:

* Confluence
* HTML
* PDF Book



// ==== Confluence

// From current folder, edit the file named *.env-confluence* with your credentials. Don't edit anything else.

// [TIP]
// ====
// ANCESTOR_ID is found by browsing Confluence page and clicking Edit button. The Ancestor Id is the pageId seen in URL such as http://localhost:8090/pages/viewinfo.action?pageId=327706
// ====

// Then run command from console:

//     $ make publishToConfluence

// The Confluence page will be found under the project page defined as *ANCESTOR_ID* in .env file.

// ==== HTML

// WARNING: FIXME

// FIXME: link:https://darshandsoni.com/asciidoctor-skins/[Theming]

// ==== PDF

// From current folder, run following command:

//     $ make publishToPDF

// The documentation will be rendered under the *build/_pdfbook.pdf* file

// NOTE: See link:https://github.com/asciidoctor/asciidoctor-pdf/blob/master/docs/theming-guide.adoc#applying-your-theme[Theming Guide]

// == Tips

// Here are few tips: 

// * link:https://github.com/asciidoctor/docker-asciidoctor[Asciidoctor Docker image]
// * link:https://bcouetil.gitlab.io/academy/BP-asciidoc.html[AsciiDoc Tips @ Zenika]

// For example *foldable source* :

// +++ <details open><summary> +++
// *opened by default*
// +++ </summary><div> +++
// [source, json]
// ....
// {
//    "plop" : "key", "value" : "value"
// }
// ....
// +++ </div></details> +++

// ==== Confluence/GIT Specific (not in PDF)
ifdef::env-github,confluencePublisherVersion[]

== Chapters

ifdef::env-github[]
* <<_cross-references.adoc#, Cross References>>
endif::[]

* <<00-index/Designs.adoc#, Designs>>
* <<00-index/Diagrams.adoc#, Diagrams>>
* <<00-index/CICD.adoc#, CICD>>

== Links within Pages

Links to content blocks within the same page are supported using AsciiDoc inline anchors and internal cross references:

[listing]
....
[[paragraph-a]]Paragraph with inline anchor

Another paragraph with internal cross-reference to <<paragraph-a>>
....

[[paragraph-a]]Paragraph with inline anchor

Another paragraph with internal cross-reference to <<paragraph-a>>

Links to sections within the same page are supported either using anchors or custom section ids:

[listing]
....
[[section-a]]
=== Section with Anchor

Paragraph with internal cross-reference to <<section-a>>
....

[[section-a]]
=== Section with Anchor

Paragraph with internal cross-reference to <<section-a>>

[listing]
....
[#section-b]
=== Section with Custom Id

Paragraph with internal cross-reference to <<section-b>>
....

[#section-b]
=== Section with Custom Id

Paragraph with internal cross-reference to <<section-b>>


[WARNING]
====
Links from one page to an inline anchor within another page are currently not supported.
====

= Paragraphs

AsciiDoc paragraphs are translated to Confluence paragraphs, supporting all typical styles, for example:

[listing]
....
This is a paragraph with *bold* text.
....

This is a paragraph with *bold* text.


[listing]
....
This is a paragraph with _italic_ text.
....
This is a paragraph with _italic_ text.


[listing]
....
This is a paragraph with `monospaced` text.
....
This is a paragraph with `monospaced` text.


[listing]
....
This is a paragraph with `*_monospaced bold italic_*` text.
....

This is a paragraph with `*_monospaced bold italic_*` text.


[listing]
....
This is a paragraph with ^super^script and ~sub~script text.
....
This is a paragraph with ^super^script and ~sub~script text.

[listing]
....
.This the title of a paragraph
The title of a paragraph will rendered using a custom CSS class `cp-paragraph-title`
....

.This the title of a paragraph
The title of a paragraph will rendered using a custom CSS class `cp-paragraph-title`

endif::[]
// ==== 

// ==== Annexes
ifdef::confluencePublisherVersion[]
include::_cross-references.adoc[leveloffset=+1]
endif::[]
// ==== Annexes