name: Pipeline Docker Build

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Build Docker Images
      env:
        IMAGE: "kalemena/mingrammer-diagrams"
        VERSION: "0.23.4"
      run: |
        docker -v
        docker pull python:3.9-alpine
        cd src/main/docker/images/diagrams
        docker build --pull --cache-from ${IMAGE}:${VERSION} \
          -t ${IMAGE}:${VERSION} \
          -f Dockerfile \
          --build-arg VERSION=${VERSION} \
          --build-arg BUILD_DATE=`date -u +"%Y-%m-%dT%H:%M:%SZ"` \
          --build-arg VCS_REF=`git rev-parse --short HEAD` .
        docker ps -a
        docker tag ${IMAGE}:${VERSION} ${IMAGE}:latest
        docker images
        docker login -u "${{ secrets.DOCKER_USERNAME }}" -p "${{ secrets.DOCKER_PASSWORD }}"
        docker push ${IMAGE}:${VERSION}
        docker push ${IMAGE}:latest
        docker logout
    